export { default as ApiTestPage } from "./api_tests/comp";
export { default as AdminDashboard } from "./admin_dashboard/comp";
export { default as CompanyInfo } from "./company-info/comp";
export { default as Login } from "./login/comp.jsx";
export { default as MainHeader } from "./main_header/comp.jsx";
export { default as NewSupportTicket } from "./new_support_ticket/comp.jsx";
export { default as Product } from "./product/comp.jsx";
export { default as Products } from "./products/comp.jsx";
export { default as Register } from "./register/comp.jsx";
export { default as Root } from "./root/comp.jsx";
export { default as SupportTicket } from "./support_ticket/comp.jsx";
export { default as MainFooter } from "./main_footer/comp.jsx";
export { default as NewProduct } from "./new-product/comp";
export { default as User } from "./user/comp.jsx";
export { default as NavBar } from "./nav_bar/comp";
export { default as Blog } from "./blog/comp";
export { default as Blogs } from "./blogs/comp";
export { default as NewBlog } from "./new_blog/comp";
export { default as LinkLikeP } from "./LinkLikeP/comp";
export { default as Terms } from "./terms/comp";
export { default as FirstSetup } from "./first_setup/comp";
export { default as Users } from "./users/comp";
export { default as Modal } from "./Modal/Modal";
export { default as Section } from "./section/comp.jsx";
export { default as ShoppingCardPage } from "./shopping_card_page/comp";
export { PG } from "./pg/pg";
export { NewProductReview } from "./new_product_review/comp";
