
POST http://localhost:4000
Content-Type: application/json
task : get_users

{
    "username" : "hamed"
}

###

POST http://localhost:4000
Content-Type: application/json
task : get_users

{
    "filters" :
}

###

POST http://localhost:4000
Content-Type: application/json
task : get_user_data_hierarchy

{
    "user_id" : "637e4be714cc596422e71b89"
}

###
POST http://localhost:4000
Content-Type: application/json
task : get_resource

{
    "_id" : "6396e064b990e52da9e78459"
}
