GET http://localhost:4000/users

###

POST http://localhost:4000/users/new
Content-Type: application/json

{
    "username" : "hamedpro",
    "password" : "hamed"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "vahidpro",
    "password" : "vahid"
}